### PR TITLE
Loading screen. Minor QoL upgrade.

### PR DESCRIPTION
**Pull request by cloud9team**
Added spinning gear on page load. Minor QoL edits :D

### CODE REVIEW

**Comment by muckelba** [comment]
Can you add the i8ln stuff to make it translatable? 😅

**Comment by ccev** [comment]
Missed opportunity to have a spinning pokeball in pmsf 🥺

**Comment by cloud9team** [comment]
Both suggestions will be added to updated pr. Nice catch.

**Comment by cloud9team** [comment]
Didn't add animated gif. The icon and text disappearing are functions of Font Awesome, which as far as I know, don't allow for custom gifs. The initial idea was to keep this as lightweight as possible.

**Comment by whitewillem** [comment]
it does allow a gif. Just have to make the complete line optional. like

$loadingIcon = '';
or
$loadingIcon = '<i class="fa fas fa-cog fa-spin fa-2x" aria-hidden="true"></i>';

**Comment by cloud9team** [comment]
I've no clue what Travis is complaining about...but pokeball gif added, along with ability to add custom html for load screen. If someone who has a better relationship with travis could take a look - be appreciated.

**Comment by whitewillem** [comment]
style ci wants you to remove the space after $noLoadingScreen for both example config and default.php
http://prntscr.com/q78rss

**Pull request merged**
