### PR TITLE
Update normal pokestop location

### PR DESCRIPTION
**Pull request by Kneckter**
Move the location of the normal pokestop sprite so it is in the same position as other stops. Not sure if anyone else had this issue with different pokestop icons but this update works with the original icon and new ones.

Normal pokestops weren't in the middle of their range or on their lat/lon like this:
image

After the changes they should look like this:
image

They should also look like they are the same size as the other pokestop icons instead of looking bigger.

### CODE REVIEW

**Comment by whitewillem** [comment]
Only reason you had to re-center it is coz you used a bigger pokestop icon. This pr just makes the original stop bigger. Im ok with this but we should replace the icon with something better then.

**Comment by Kneckter** [comment]
Do you have a higher resolution of the original pstop? I can match sizes so it looks better but I don't have a that specific icon. I can replace the original with a different one if you don't.

**Comment by whitewillem** [comment]
I don't. Feel free to include a new pokestop icon. Just make sure its not a huge image. You can use https://tinypng.com/ to optimize it.

**Comment by Kneckter** [comment]
One one will match the style of the lured stops in PMSF and is optimized.

**Comment by ccev** [comment]
stats page also uses an old style icon for lured stops. To have it all unified it'd be cool to change that icon too (and delete the old one)

**Comment by Kneckter** [comment]
I saw that icon but couldn't figure out where it was used so I left it. Now I know and updated it.
image

**Pull request merged**
