### PR TITLE
add form to quest search

### PR DESCRIPTION
**Pull request by plinytheelder**
quest search bar doesn't show form and currently just defaults to normal. this fixes that.

also, quest search bar is still broken so re-proposing my quickie fix of shortening the gym name so that users are able to scroll through quests on mobile.

### CODE REVIEW

**Comment by TiMXL73** [comment]
I'm not using RDM but this seems to simply return a filled `quest_pokemon_formid` that isn't used by the calling function `searchForItem` in `static/js/map.js` which uses a static `_00` for the images.

Using the same `formStr` scheme and validation as everywhere else, this is what my modified file looks like (not all highlighted lines are modified, it's the general area):

https://github.com/TiMXL73/PMSF/blob/mad_rm/static/js/map.js#L2853-L2878

**Comment by plinytheelder** [comment]
current map.js is an if/else and is just defaulting to 00 right now. change I made works and for me on rdm. not sure how mad does it.

**Comment by TiMXL73** [comment]
There is an if/else for forms but that's for displaying Pokéstop and their quest popup on the map, not the search result window.

I'm not sure how forms would display correctly in the search result list popup window without modifications considering is is a fixed `_00` that is used for the pokemon images without any if/else regarding forms: https://github.com/whitewillem/PMSF/blob/develop/static/js/map.js#L2845

Glad it's working for you like this and I won't comment any further.
image

**Comment by fosJoddie** [comment]
FWIW - in MAD:

The `form_value` is inside the `quest_reward` "json-as-a-db-column" in `trs_quest` FYI - and is filled when known. 
relevant json-snippet
```
[ {
"type": 7,
...
"pokemon_encounter": {
...
"pokemon_display": { ...
   "form_value": 78, ...} 
}
}
]
```

full example
```
[{"type": 7, "exp": 0, "item": {"item": 0, "amount": 0}, "stardust": 0, "candy": {"pokemon_id": 0, "amount": 0}, "avatar_template_id": "", "quest_template_id": "", "pokemon_encounter": {"pokemon_id": 103, "use_quest_pokemon_encounter_distribuition": false, "pokemon_display": {"is_shiny": false, "weather_boosted_value": 0, "weather_boosted_description": "NONE", "gender_value": 1, "form_value": 78, "costume_value": 0}, "is_hidden_ditto": false, "ditto_display": {"is_shiny": false, "weather_boosted_value": 0, "weather_boosted_description": "NONE", "gender_value": 0, "form_value": 0, "costume_value": 0}}}]
```

**Comment by plinytheelder** [comment]
ooops. shouldn't have made a pull request while drinking. TiMXL73 has the proper fix in map.js

**Pull request closed without merging**
